# This is a simple GitHub Action that prints a name passed as an input.
# It demonstrates how to use the `composite` action type.
# The action takes a single input, `name`, and prints a greeting message.

name: 'Sandeep Lightning Greet (Docker)'
description: 'A fast greeting action running inside a Docker container.'
author: 'Sandeep kumar patel'

inputs:
  name:
    description: 'Your name'
    required: true
  place:
    description: 'Your location'
    required: true
  age:
    description: 'Your age'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: []

branding:
  icon: 'terminal'
  color: 'blue'