# Name of the file test
name: Basic Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-action:
    name: Test Print Name Place Age Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run the custom action with sample data on docker
        uses: ersandeep977/sandeep-lightning-greet@v2
        with:
          name: "Sandeep"
          place: "India"
          age: "30"
